version: "3"

services:
  traefik:
    image: traefik:alpine
    command: "traefik --docker --docker.swarmmode --docker.domain=doare --docker.watch --api"
    ports:
      - 8080:80
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.toml:/traefik.toml
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 50M
      placement:
        constraints: [node.role == manager]
  consul:
    image: progrium/consul
    command: -server -bootstrap -log-level debug -ui-dir /ui
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    networks:
      - proxy
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  proxy: