logLevel = "DEBUG"
defaultEntryPoints = ["http","https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "mydomain.com"
watch = true
exposedbydefault = false

[acme]
email = "herlon@mydomain"
storage = "traefik/acme/account"
entryPoint = "https"
onDemand = false
OnHostRule = true
acmeLogging = true

[acme.httpChallenge]
entryPoint = "http"

[consul]
endpoint = "consul:8500"
watch = true
prefix = "traefik"

[consulCatalog]
endpoint = "consul:8500"
domain = "mydomain.com"